### ISSUE TITLE
Document accessibility requirements

### ISSUE THREAD

**Issue by AngelQuicksey** [cagov/ui-claim-tracker#10]
### Task
Document accessibility criteria that we are required to meet

### Details / Context

- Requires collaboration between engineering and design
- A lot of content already exists in the draft EDD Web Development Standards document

_Example EDD Web Development Standards section on accessibility:_

> Digital content such as websites, documents, and applications must be designed, developed, and tested with accessibility in mind to ensure equal access to people of varying capabilities. Assembly Bill 434 directs all state entities to comply with California Government Code Section 7405 and Section 11135 and the Web Content Accessibility Guidelines (WCAG) conformance level AA and to certify every two years that their public-facing websites are accessible. Section 7405 requires compliance with the accessibility requirements of Section 508 of the federal Rehabilitation Act of 1973, which uses WCAG as the required standard. EDD’s current standard is to adhere to WCAG 2.1 AA requirements.

### Acceptance Criteria

- [x] CA UI Claim Tracker team has documented our required accessibility obligations
- [x] Team has discussed how to meet those obligations throughout the project lifecycle

**Comment by nicoleslaw** [comment]
So far, I've read through EDD's docs and the Department of Rehabilitation's site to document requirements that directly relate to our work. I organized these into topics [here](https://docs.google.com/document/d/1lQX_g78y93za6cIPAgFy52LUI1wRn39gbedb20OdU3I/edit#heading=h.f5h8lj8g5l1m).
