### ISSUE TITLE
Identify UAT process and incorporate into timelines

### ISSUE THREAD

**Issue by dianagriffin** [cagov/ui-claim-tracker#105]
### Acceptance Criteria

  - [ ]

**Comment by JessiBull** [comment]
this seems redundant of #89. Could we make this more specific and close whichever ticket isn't needed?

**Comment by dianagriffin** [comment]
@JessiBull #89 is for the review processes that go through WCUG (accessibility, usability) whereas this ticket is for the UAT process which goes through UIB for final signoff before launch (based on my understanding of how it worked last year).
