### ISSUE TITLE
Lightweight iteratations on prototype based on research findings

### ISSUE THREAD

**Issue by nguyen-tina** [cagov/ui-claim-tracker#108]
### Details / Context
If the research findings point to a direction where the design can make immediate updates that will improve the prototype for further testing, the Design team can make rapid updates to ready the prototype for further testing within this research sprint. 

### Acceptance Criteria

- [x] Identify possible prototype changes after Day 1 research sessions
- [x] Make prototype updates from Day 1 sessions
- [x] Identify possible prototype changes after Day 2 research sessions
- [x] Make prototype updates from Day 2 sessions
- [x] Identify possible prototype changes after Day 3 research sessions
- [x] Make prototype updates from Day 3 sessions

**Comment by AngelQuicksey** [comment]
@nguyen-tina Can you check the acceptance criteria where this has been done or add a comment if there were no identified changes out of Day 1 research.

**Comment by nguyen-tina** [comment]
Prototype updates made from Day 0
