### ISSUE TITLE
Create Azure Log Analytics Workspace

### ISSUE THREAD

**Issue by dgoeke** [cagov/ui-claim-tracker#116]
### Description

As described in the [Technical Foundations document](https://docs.google.com/document/d/1i2pj7_3n0VjqqztOepkd2VcG7JA8N9Tg5P76GSI8tzw/edit#heading=h.mxcw9gw0rq41), the best practice for logging in Azure is to create a Log Analytics Workspace and configure App Service to forward its logs there. We should also update the Claims Tracker app to emit a log event for each request in order to facilitate debugging and to confirm that logging in Azure is correct.

### Acceptance Criteria

  - [ ] Logs Analytics Workspace created
  - [ ] App Service logs forwarded to LAW
  - [ ] Request logging added to Claims Tracker app

**Comment by lomky** [comment]
Completed via #171 and existing setup by CDT
