### ISSUE TITLE
Refine the Footer Component

### ISSUE THREAD

**Issue by lomky** [cagov/ui-claim-tracker#118]
### Description

As implemented in #74 the behavior of the footer doesn't quite match [EDD](https://edd.ca.gov/), showing a single column instead of two. This ticket is to more perfectly match the experience of the main EDD site.

### Acceptance Criteria

  - [ ] Our footer matches the EDD footer on smaller screens

**Comment by lomky** [comment]
one thing to try:  replicate the UL/LI format of the EDD footer, ensuring that each LI element has these matching 3 attributes: 
![EDD footer css code](https://user-images.githubusercontent.com/6129479/115618572-e25b8000-a2c0-11eb-9a08-5c24c3dc2372.png)

**Comment by kalvinwang** [comment]
Rating it a S with timebox to 1h, since the single column looks fine, it just doesn't quite match EDD existing footer behavior
