### ISSUE TITLE
Tech Spec: mTLS Connection with API Gateway

### ISSUE THREAD

**Issue by kevmo** [cagov/ui-claim-tracker#119]
### Description
ClaimTracker will access the API gateway using mTLS. Research technical requirements for this. 

### Acceptance Criteria

  - [ ] Technical specifications described in one doc for research around issue
  - [ ] Integrate relevant details & decisions into Technical Foundation document(s)

**Comment by rocketnova** [comment]
@kalvinwang @lomky A draft of this [documentation](https://docs.google.com/document/d/14LyLIRdH9BlYW7-6iLuizf4QwISSZmzTh7LDASCanSY/edit) is ready for review

**Comment by kalvinwang** [comment]
Completed splitting the doc between Technical Overview and Foundations docs
