### ISSUE TITLE
Create Loading state for Claim Tracker

### ISSUE THREAD

**Issue by nguyen-tina** [cagov/ui-claim-tracker#121]
### Task
We need to define a loading state for the page, in case the internet connection is slow.

### Details / Context
The loading state should work on mobile and desktop, no matter the browser or device. It should be the first thing to load on a page.

### Acceptance Criteria

- [x] Style designed for desktop and mobile

**Comment by nguyen-tina** [comment]
So far, I'm thinking of Figma's loading state-- I like how the bar moves across the page to show progress. Since the global header has a bar at the bottom, I wonder if we can borrow from that experience for our own loading style.

![Screen Shot 2021-04-28 at 1 51 13 PM](https://user-images.githubusercontent.com/17328158/116450019-cc9e0b80-a828-11eb-8ccd-1d2844203b72.png)

I'll reach out to EDD to see what loading styles they have, to sync up for consistency.

**Comment by nguyen-tina** [comment]
There will be three sections of loading time:
- User makes request to UIO + authentication, passes to Azure
- Azure generates page components (very fast)
- Response time of API gateway (actual fields, hopefully should also be fast).

Loading state can be displayed for both second and third sections.

**Comment by nguyen-tina** [comment]
Comments continued in [Slack Thread](https://nava.slack.com/archives/C01Q5640YFR/p1619632351017100)

**Comment by lomky** [comment]
We'll likely be able to use a [drop-in React effect!](https://github.com/gokcan/react-shimmer) for the shimmer sections!

**Comment by nicoleslaw** [comment]
Should we close this out?

**Comment by lomky** [comment]
@nicoleslaw design is done - this is in eng's backlog now.  you can remove the design label maybe?
