### ISSUE TITLE
Serve application from /claimstatus

### ISSUE THREAD

**Issue by kalvinwang** [cagov/ui-claim-tracker#122]
### Description
The Claim Tracker application needs to live at /claimstatus because the IDM Oracle Webgate plugin/server expects the "context root" to be /claimstatus, and all other pages must be child paths/routes. 

### Acceptance Criteria

  - [ ] the existing Claim Tracker page should be served from /claimstatus, and / (root) should redirect to /claimstatus

**Comment by lomky** [comment]
[NextJS Pages](https://nextjs.org/docs/basic-features/pages)
[NextJS Redirects](https://nextjs.org/docs/api-reference/next.config.js/redirects)
[NextJS Basepath](https://nextjs.org/docs/api-reference/next.config.js/basepath)
