### ISSUE TITLE
Update default Next.js error pages

### ISSUE THREAD

**Issue by kalvinwang** [cagov/ui-claim-tracker#123]
### Description

- If there's an issue with the Claim Tracker web application itself, we should show the appropriate error page (404 page not found or 5xx server-side error)
- Next.js has default 404 and 500 error pages (see below); we can [customize](https://nextjs.org/docs/advanced-features/custom-error-page) them.
- The Claim Tracker 404/500 error pages should look obviously different from the UIO 404/500 error pages, s that when a user who takes a screenshot of the page, it's clear whether the error was in UIO vs Claim Tracker. The default Next.js error pages are sufficiently different already. However, we may want to customize the Next.js error pages to look more like part of UIO than they do by default.

Context:
-  If there's an issue with the IDM integration, the Claim Tracker page won't be loaded, and an IDM error page will be shown, hopefully
- If there's an issue reaching the API gateway, we'll return some kind of inline error, TBD in a separate ticket.

Default 404 page:
![image](https://user-images.githubusercontent.com/82277/116940035-4d02a900-ac3b-11eb-863f-f36fbf4f9747.png)

### Acceptance Criteria

  - [ ] On staging, should show the appropriate error page (404 or 5xx) when triggered

**Comment by nguyen-tina** [comment]
Mocked up new 404 design and posted to channel for review

**Comment by nguyen-tina** [comment]
Updated [proposal](https://docs.google.com/document/d/1SX5-cKj10MdjMqdacHAsKZyasd2vaERWSRTCfPL3-J4/edit#heading=h.qri95rtk659n) for 404 and 500 content. Handing off to Engineering.
