### ISSUE TITLE
Convert to a querystring localization strategy to support our real URLs

### ISSUE THREAD

**Issue by lomky** [cagov/ui-claim-tracker#140]
### Description

By default NextJS Support subpath (`example.com/es/path`) and subdomain locale strategies, however we only get to live on `/claimstatus` and cannot alter our path nor domain. 

Previously on [unemployment](https://github.com/cagov/unemployment) we handled this with [i18next-browser-languageDetector](https://github.com/i18next/i18next-browser-languageDetector) with plugs into i18next. _However_ plugging this into our [next-i18next](https://github.com/isaachinman/next-i18next) configuration and overriding nextJS's [i18n routing](https://nextjs.org/docs/advanced-features/i18n-routing) will take some work. [Here is one person](https://stackoverflow.com/a/63749016/784829) who has it working in their TS NextJS app.

### Acceptance Criteria

  - [ ] i18n works in the main app & components
  - [ ] i18n works in Jest tests
  - [ ] i18n displays the English strings in Storybook (no locale change functionality here)
  - [ ] Locale detection is handled via querystring
  - [ ] Locale detection does not change the URL
  - [ ] Nice to have: fallback of browser language detection works still

**Comment by kalvinwang** [comment]
Disregard if this is less maintanable, but can we consider directly implementing support for `querystring (append ?lng=LANGUAGE to URL)` since that's the only function we need from the languageDetector library? If Next.js supports arbitrary query parameters already, it might just be a few lines of code to toggle the locale when the lng url param is detected.

**Comment by lomky** [comment]
It turns out we have full controll of our path after `/claimstatus` - nextjs path-based localization adds the string after the basepath, so now that we use that, our translation process will likely work fine. Closing this ticket as unneeded.

![image](https://user-images.githubusercontent.com/6129479/119499917-34b31500-bd35-11eb-8650-483aec6d3d1e.png)
