### ISSUE TITLE
Ensure backend URLs are only accessible from EDD/Nava IPs

### ISSUE THREAD

**Issue by kalvinwang** [cagov/ui-claim-tracker#143]
### Description
The backend URLs should only be accessible from IPs belonging to IDM, and Nava. We'll need to get a list of the IDM IPs. From googling, this is a configuration page in Azure App Service ([docs](https://docs.microsoft.com/en-us/azure/app-service/app-service-ip-restrictions#set-an-ip-address-based-rule)).

This change should be applied in every environment.

### Acceptance Criteria

  - [ ] See description
  - [ ] Document the access restrictions

**Comment by kalvinwang** [comment]
@lomky i think you've finished this ticket? you can close if so, thanks! i just added https://github.com/cagov/ui-claim-tracker/issues/234 as the followup (take a look and see if it makes sense).

**Comment by lomky** [comment]
Configured & documented in the Technical Foundations doc. Follow-up ticket for a nicer, FrontDoor-based config: #234
