### ISSUE TITLE
Implement error & alert system when any critical environmental variable is missing. 

### ISSUE THREAD

**Issue by kevmo** [cagov/ui-claim-tracker#176]
### Description
Environmental variables are critical to the proper functioning of Claim Tracker. When they are not present, the app will be non-functional, i.e. "The app is down."  Implement an alert system whenever the environmental variables are missing. 

1. Add code
2. Set up alert in Azure or ask CDT, depending on result of #218 

### Acceptance Criteria

  - [x] If a env variable doesn't exist on prod, a Sev 3 alert should be triggered
  - [x] If a env variable doesn't exist on lower envs, a notification to CA UI eng should be triggered

Possible followups for other tickets if needed: 
  - The development team is alerted whenever environmental variables are not present. 
  - Make sure code in ` pages/claimstatus/index.tsx` which loads env variables triggers alert if necessary.

**Comment by rocketnova** [comment]
We discussed what we want to show if this happens and we want to show a 500 error
