### ISSUE TITLE
Investigate Azure alert

### ISSUE THREAD

**Issue by kalvinwang** [cagov/ui-claim-tracker#184]
### Description
Figure out why the Failure Anomalies went off on staging, and why there were 5k+ requests when we don't have any actual traffic yet.

Could be related to health check in #149 

### Acceptance Criteria

  - [ ] Write up results and any next steps needed

**Comment by rocketnova** [comment]
Looking at the Azure Portal, it looks like Azure Healthcheck is disabled for all environments, so I don't think this is related to healthcheck.

**Comment by rocketnova** [comment]
@kalvinwang I investigated this and determined that the email error messages we have been receiving are not related to Claim Tracker. I think we need to ask for some email alert tuning.

**Comment by kalvinwang** [comment]
Thanks! I think we can close this ticket now then?

**Comment by rocketnova** [comment]
@kalvinwang I think we should leave this open to track the effort to do the alert tuning.

**Comment by kalvinwang** [comment]
CDT has updated the email alerts to only send Claim Tracker alerts to the -alerts email, and last year's alerts to the -eng email.
