### ISSUE TITLE
Refine next steps hierarchy in Claim Status section

### ISSUE THREAD

**Issue by nicoleslaw** [cagov/ui-claim-tracker#188]
### Description
Incorporate feedback from UIB and WCUG into designs for launch, and communicate any major changes to engineering.

### Feedback

"Container around Next Steps draws focus away from important claim status information. Claim status should have more visual prominence. Right now it looks like intro text." — WCUG

### Acceptance Criteria

- [x] Explore what a more prominent status would look like (e.g., pizza tracker or status tag)
- [x] Share past visual explorations with WCUG in working session for context and history

**Comment by nguyen-tina** [comment]
WCUG has reviewed the designs, and ok-ed us to explore Next Steps iterations for post-MVP.

**Comment by nicoleslaw** [comment]
Moving this into this sprint. WCUG would like to see some visual exploration with the updated content, ex:

- Where did we get on the "pizza tracker" concept
- What would a status tag look like
- Could we explore icons or other visual refinements

I suggested that we could share some of the past work and ideas in our next sync, 7/15.

**Comment by nguyen-tina** [comment]
Presented this to WCUG last week, working on iterating this version to present to UIB currently.

**Comment by nguyen-tina** [comment]
Initial explorations have been complete. Next explorations will occur in a new ticket.
