### ISSUE TITLE
Get test data from EDD for fields we're definitely using

### ISSUE THREAD

**Issue by kalvinwang** [cagov/ui-claim-tracker#201]
### Description

Although we might know _all_ of the fields we need from EDD yet, we do know some (7 fields) that we will definitely be using. Right now we are only receiving one field back (not one of the fields we foresee using) from the API gateway. 

It would be helpful to get test data from the API gateway for the fields we know we will definitely be using prior to waiting until we have nailed down the final fields, so that:
- We can verify that our code can handle these fields
- We can verify the range and type of data that we'll need to validate and display handle

### Acceptance Criteria

  - [x] Receive test data for the known 7 fields

**Comment by rocketnova** [comment]
We checked in with Diana who let us know that we already received test data for the fields we currently know about. I'm going to close this ticket. We should open another ticket to get test data once we know the final set of fields we'll need.
