### ISSUE TITLE
Improve alert banner interaction

### ISSUE THREAD

**Issue by nguyen-tina** [cagov/ui-claim-tracker#211]
### Description

Post-MVP launch, explore ways to improve the banner interaction including permanently dismissing the alert banner or introducing a survey to gather feedback from claimants.

### Acceptance Criteria
- [ ] (Engineering) Discuss what it would take technically to permanently dismiss the banner
- [ ] (Product) Touch base on survey initiative, and whether the alert banner is the appropriate place to surface the survey
- [ ] Make a decision about the next development of the alert banner

**Comment by nicoleslaw** [comment]
I think we can close this since we're removing the banner.
