### ISSUE TITLE
Only continuous deploy to staging from main branch

### ISSUE THREAD

**Issue by rocketnova** [cagov/ui-claim-tracker#212]
### Description

Currently, we have continuous deployment enabled for the staging environment for all Pipeline builds, this includes any manual Pipeline builds from feature branches. Instead, we would prefer to only have automated releases to staging if the build is on the `main` branch.

### Acceptance Criteria

  - [x] Staging only triggers for builds from the `main` branch

**Comment by rocketnova** [comment]
@kalvinwang made the configuration changes. I've confirmed that pipeline runs for the `main` branch are still being auto-deployed, but due to some unexpected static code analysis failures, I'll need to wait to verify non-`main` branch deploys.

**Comment by rocketnova** [comment]
I was able to confirm today that a successful pipeline run of a non-`main` branch did not trigger automatic deploy on staging. Closing this ticket.

**Comment by rocketnova** [comment]
I'm re-opening this ticket because we appear to have had a regression.

**Comment by kalvinwang** [comment]
This was fixed on 6/3 but CDT reverted my change on 6/8. I've applied the fix again and will follow up with CDT to see why it was reverted.
