### ISSUE TITLE
Set up availability test to monitor end-to-end uptime

### ISSUE THREAD

**Issue by kalvinwang** [cagov/ui-claim-tracker#213]
### Description

1. Set up a "Standard Test" in Application Insights (with a custom header for a unique number) to monitor end-to-end uptime on both test and production, sending alerts to our new alert email. [Instructions](https://docs.microsoft.com/en-us/azure/azure-monitor/app/availability-standard-tests) here. This isn't true end-to-end, since it excludes IDM, but includes everything else. We should test a URL that bypasses IDM, since we don't want BPO login to block

2. Consider using Health Check in App Service, in addition (result: created separate ticket [here](https://github.com/cagov/ui-claim-tracker/issues/396))

### Acceptance Criteria
  - [x] Add the ping test IPs to our list of allowed IPs, using the service tag mentioned [here](https://docs.microsoft.com/en-us/azure/azure-monitor/app/availability-private-test)
  - [x] Ask CDT to move Front Door's Health Probes to a new /health endpoint
  - [x] Verify the test is working on test and production 
  - [ ] Document all of the above

**Comment by rocketnova** [comment]
@kalvinwang It looks like the [Azure guide](https://docs.microsoft.com/en-us/azure/azure-monitor/app/monitor-web-app-availability) you linked to requires a URL that is available on the public internet:
> The URL can be any web page you want to test, but it must be visible from the public internet. 

What do you want the success criteria for this ping alert to be?

**Comment by kalvinwang** [comment]
Oops just saw this comment! @rocketnova the production Front Door URL is a public URL (that now blocks non-Nava/EDD IPs, but we can theoretically add the Application Insights IPs?)

**Comment by kalvinwang** [comment]
Updated the body of this ticket
