### ISSUE TITLE
Provide EDD with documentation on specific alerts

### ISSUE THREAD

**Issue by kalvinwang** [cagov/ui-claim-tracker#216]
### Description
Once remaining alerts are live (in #174, #176, #217, maybe more TBD) we should provide EDD with documentation on them (when they are triggered and who receives them).

Also, we should re-request the list of EDD emails that need to be notified on Sev 3 alerts (see "Claim Tracker SLA" thread, document in SLA, and re-send to EDD.

Also, we should update the SLA to include the new Azure SLA link from CDT, and the updated "Severity 3 alerts should go to the the official EDD incident email list, whereas Sev 4/5 can be regular email correspondence." line from the On-Call Process doc

### Acceptance Criteria

  - [ ] Send documentation on all alerts to EDD on "Claim Tracker SLA" thread

**Comment by rocketnova** [comment]
Closing this ticket in favor of other documentation tickets.
