### ISSUE TITLE
Coordinate with EDD to translate content to Spanish

### ISSUE THREAD

**Issue by nguyen-tina** [cagov/ui-claim-tracker#226]
### Description
All the content on the Claim Tracker page needs to be translated to Spanish. Work with EDD to translate over

### Acceptance Criteria

- [ ] Content for all launch scenarios has been defined
- [ ] Share content with translation analyst
- [ ] Share translated content from EDD with engineering

**Comment by nicoleslaw** [comment]
It seems that CA is managing this and we don't need to be an intermediary. If that changes, I will take care of this task.
