### ISSUE TITLE
Create usability testing interview guide and note-taking documents

### ISSUE THREAD

**Issue by AngelQuicksey** [cagov/ui-claim-tracker#23]
### Details / Context
Set up the infrastructure required to conduct usability testing. 

As a requirement, the scope of what we are testing should be clearly defined. (#85 Recruiting plan)

### Acceptance Criteria
- [x] Create interview guide ([link](https://docs.google.com/document/d/1KWHgJ0sgWX42oXCkHoa4bIS7V-zL48z2sgAumXUyOV0/edit#))
- [x] Create note-taking template ([link](https://docs.google.com/document/d/1f5qaObFERhZtY_YTOAlxRIxCdk6GNvYg2bFEsfzGzR8/edit#))
- [x] Create schedule sign-up for observers ([link](https://docs.google.com/spreadsheets/d/1g-99lNvVA7K9TAoZ3A_X02jgKey-KG1v1lLiTyom0P0/edit#gid=1723666543))
- [x] Create observation document ([link](https://docs.google.com/document/d/1uOD-lLzZHQgQeuR9CmCPS9rWNsUHJD1kEuCNxGJQj7I/edit#))

After creating moderator guide, #22 Recruit.

**Comment by AngelQuicksey** [comment]
@tina Can you break this into 3 tickets? 

Small | Create recruiting/outreach plan
Small | Create usability testing protocol and notetaking documents

**Comment by nicoleslaw** [comment]
@nguyen-tina @dianagriffin The [interview guide](https://docs.google.com/document/d/1KWHgJ0sgWX42oXCkHoa4bIS7V-zL48z2sgAumXUyOV0/edit#) is ready for an initial review. It's somewhere between an outline and a first draft but I'd love any early input since I am on vacation on Friday.

I also updated the notes doc template but will finalize that once we're closer on the guide.

**Comment by nicoleslaw** [comment]
These docs are all ready for internal review and comments! I also made a consent form and auto-tracked spreadsheet ([link](https://docs.google.com/forms/d/1PiWRA-gs-JuHi8USMJYlSSVOeAib471jg4f6bit-NT4/edit)).

**Comment by AngelQuicksey** [comment]
Can I close this ticket @nguyen-tina or do these need additional review?

**Comment by nguyen-tina** [comment]
Go ahead and close
