### ISSUE TITLE
Load the ClaimTracker page in two stages

### ISSUE THREAD

**Issue by lomky** [cagov/ui-claim-tracker#230]
### Description

At the moment the ClaimTracker page is loaded in one go after recieving a response from the API. Instead We'd like to deliver the user-agnostic outline of the page with the internal sections in a loading state, which is then filled with user-specific information upon the response from the API. The loading state was already defined in the components in #121 but will need to be hooked up to the API as a part of this ticket.

### Acceptance Criteria

- [ ] Initial Page Load no longer depends on the API response
- [ ] While awaiting the API response the app displays in the `loading` state 
- [ ] When we recieve the API response the loading state is disabled and the user information is displayed.

**Comment by rocketnova** [comment]
Closing in favor of #231
