### ISSUE TITLE
Regenerate client certificates

### ISSUE THREAD

**Issue by rocketnova** [cagov/ui-claim-tracker#239]
### Description

Prior to alpha launch, we need to generate new client certificates. We discovered that our current certificates do not meet the signature algorithm requirement.

### Acceptance Criteria

- [x] Generate new certificates for each environment
- [x] Certificates are updated in the API gateway
- [x] Certificates are updated in Azure 
- [x] Certificates have been stored securely
- [x] #90 has been updated with new expiration date
- [x] Documentation has been updated for the new certificates
- [x] Test new certificates (and none others) work for each environment

**Comment by kalvinwang** [comment]
Comprehensive list of acceptance criteria (I got here from #90), thanks!

**Comment by rocketnova** [comment]
Certificates have been made available a la https://docs.microsoft.com/en-us/azure/app-service/configure-ssl-certificate-in-code#make-the-certificate-accessible

**Comment by rocketnova** [comment]
This ticket is now complete!
