### ISSUE TITLE
Connect Azure Devops to Slack

### ISSUE THREAD

**Issue by kalvinwang** [cagov/ui-claim-tracker#249]
### Description

We would like to be notified in Slack when deploys begin and end in Azure Devops. This is more than a convenience because Veracode occasionally fails during a deploy and requires a manual reset, and it's otherwise easily missed. (We tried to have it moved to CI instead of CD but that created even larger issues). 

### Acceptance Criteria

- [ ] Notify in Slack when a deploy begins and when it's complete in Azure Devops, in all environments.

**Comment by kalvinwang** [comment]
Deploys for all four environments now notify on start and completion in the eng slack channel

**Comment by rocketnova** [comment]
To setup Slack notifications for Azure Devops pipelines:
- Add the [Azure Pipelines Slack app](https://nava.slack.com/apps/AFH4Y66N9-azure-pipelines) to your instance of Slack
- Authenticate in Slack: `/azpipelines signin`
  - Make sure to authenticate to the _correct_ instance of Azure Devops (it's easy to log into the wrong thing)
- In Azure Devops, navigate to the Pipeline you want to get notifications about
- In Slack, subscribe to the pipeline : `/azpipelines subscribe [url from previous step]`

Microsoft documentation about this Slack app: https://docs.microsoft.com/en-us/azure/devops/pipelines/integrations/slack?view=azure-devops

- To remove all notifications: `/azpipelines unsubscribe all [project url]`
- To log out of Azure in Slack: `/azpipelines signout`

**Comment by rocketnova** [comment]
We added notifications for the new pipelines for the new environments (#476).
