### ISSUE TITLE
Should we use Next.js instead of our previous Node/Express/Webpack setup?

### ISSUE THREAD

**Issue by lomky** [cagov/ui-claim-tracker#25]
### Task

Work through the Claim Tracker Technical plan NextJS section and make a call for our existing system or moving the NextJS

### Details / Context

[See Claim Tracker Technical Planning](https://docs.google.com/document/d/1egaCCgjpnlxV2RRmdCZDjgSJkS9BiGuZG8TuuYRlxes/edit?usp=sharing)

### Acceptance Criteria

  - We have chosen our framework

**Comment by kalvinwang** [comment]
We're going to defer this a few more days to see if the third engineer has experience or input here. We'll make the final decision by the time CDT has set up our infrastructure (end of next week hopefully)

**Comment by lomky** [comment]
We're going to go with NextJS. 
- The good documented and sane defaults will better support a maintainable codebase that is easy to onboard folks to and potentially hand off.
- We won't have to spend as much (or any) time tweaking webpack
- most other factors are a tossup
