### ISSUE TITLE
Resolve SNAT port exhaustion issue

### ISSUE THREAD

**Issue by kalvinwang** [cagov/ui-claim-tracker#254]
### Description

We're seeing a high number of connections ([SNAT port exhaustion issue](https://github.com/cagov/ui-claim-tracker/issues/185)) to the API Gateway and we should be able to reuse them by enabling HTTP Keep-Alive. Consider using [this library](https://github.com/node-modules/agentkeepalive)

If this is done after #217, you'll need to create a bunch of requests to test whether this is actually working (e.g. by reverting #217 temporarily)

### Acceptance Criteria

- [ ] Deploy branch to new internal environment and confirm in Azure's "Diagnose and solve problems" dashboard that port exhaustion is no longer an issue

**Comment by lomky** [comment]
Closing! Work will continue in #478
