### ISSUE TITLE
Iterate on process flow for MVP

### ISSUE THREAD

**Issue by nicoleslaw** [cagov/ui-claim-tracker#278]
### Description

Update LucidChart for scenarios and content variations

### Acceptance Criteria

- [x] Update LucidChart to match content and system logic
- [x] Pair with @dianagriffin and @rocketnova

**Comment by nicoleslaw** [comment]
@rocketnova @dianagriffin I added a new page to the Lucidchart and included sticky notes where I need more info. I wonder if we might chat about this and run it by Vicky once we're aligned?

**Comment by rocketnova** [comment]
@nicoleslaw Thanks for the ping on this. The Lucidchart makes sense to me and I appreciate the sticky notes since I share those questions.

**Comment by nicoleslaw** [comment]
I set up time for us to sync on this later this afternoon.

**Comment by nicoleslaw** [comment]
I think we're all set here but we can open a new ticket if any further questions come up.
