### ISSUE TITLE
Investigate why deploys take 10x longer on staging

### ISSUE THREAD

**Issue by kalvinwang** [cagov/ui-claim-tracker#279]
### Description

Staging deploys take 15-25 minutes when internal/staging/prod only take 1-2 minutes. Figure out why and how we might fix.

### Acceptance Criteria

- [ ] Create a ticket for how we can speed up staging deploys (or do it if < 1h, or document why we can't/won't speed it up)

**Comment by rocketnova** [comment]
This could be because Lighthouse runs on staging deploys, but not other deploys. Because Lighthouse runs #361 are currently not working, it's hard to determine if that's the cause.

**Comment by rocketnova** [comment]
This is no longer happening.
