### ISSUE TITLE
Gather requirements based on UIMOD data fields and handling

### ISSUE THREAD

**Issue by dianagriffin** [cagov/ui-claim-tracker#28]
### Task
Coordinate with EDD to understand UIMOD fields and data handling (e.g. update cadence), and validate status mappings.

### Acceptance Criteria

  - [ ] Business logic/requirements related to UIMOD data fields is documented (in the product brief or a linked document)

**Comment by dianagriffin** [comment]
3/8 - Emailed to request the full UIMOD data dictionary from Al / Ravi / Amarjeet as a starting point to familiarize ourselves with the entities and fields available, recognizing that additional documentation/discussion will likely be needed to narrow down our requirements.

**Comment by dianagriffin** [comment]
We have received data dictionaries for Claim, Claimant, Monetary, Stop Pay Alert, and Issues, and had an initial walkthrough discussion with Ravi and Amarjeet. We will continue to refine our business logic requirements through collaboration and validation with UIB and the UIO team.

**Comment by JessiBull** [comment]
@dianagriffin should this move back to backlog for the sprint since it's dependent on 75,78, 60?
