### ISSUE TITLE
Coordinate planning and implementation of linking between Claim Tracker and UIO

### ISSUE THREAD

**Issue by dianagriffin** [cagov/ui-claim-tracker#29]
### Task
Coordinate planning for user flows/linkage between Claim Tracker and UIO.

A user needs to be able to move between the UIO homepage and the Claim Tracker. 

Dependency: Defining launch strategy

### Acceptance Criteria

  - [x] There's a clear design for the changes that need to be made on UI Online (button)
  - [x] There's a clear method for users to navigate to UIO from the Claim Tracker.

**Comment by kalvinwang** [comment]
UIO and UIO Mobile as well (see Slack)

**Comment by nicoleslaw** [comment]
Can we close this one out?
