### ISSUE TITLE
Installing pino-applicationinsights has broken storybook builds

### ISSUE THREAD

**Issue by rocketnova** [cagov/ui-claim-tracker#299]
### Description

Sadly, #288 broke storybook builds. See https://github.com/cagov/ui-claim-tracker/runs/3023514358?check_suite_focus=true. `yarn storybook-build` is also broken locally for `main`.

If this takes more than a day or two, consider whether it does make sense to use pino-applicationinsights

### Acceptance Criteria

- [ ] Storybook builds work again

**Comment by lomky** [comment]
Poked at this for a minute - the sb build fails whether isAzureEnv is true or false, and succeeds if you comment out the await createWriteStream, so its something in the actual build step there
