### ISSUE TITLE
Coordinate with EDD to understand required pre-launch testing/review processes

### ISSUE THREAD

**Issue by dianagriffin** [cagov/ui-claim-tracker#30]
### Task
Find out what's involved in required pre-launch testing/review processes (e.g. accessibility testing, usability review, user acceptance testing, security assessment and authorization) -- especially timelines.

- @dianagriffin will take point on confirming process/expectations for security assessment (Todd Ibbotson) and UAT (Alex/Al)

### Acceptance Criteria

- [ ] Process/expectations identified for security assessment and UAT
- [ ] Required pre-launch testing/review processes have been incorporated into our MVP delivery plan.

**Comment by AngelQuicksey** [comment]
Need to confirm review/testing timeline for accessibility, content, and translation with WCUG

**Comment by AngelQuicksey** [comment]
Angel to confirm review expectations/points of contact/timelines async with WCUG

**Comment by AngelQuicksey** [comment]
Created new ticket for WCUG coordination.
