### ISSUE TITLE
Rename backend functions

### ISSUE THREAD

**Issue by rocketnova** [cagov/ui-claim-tracker#317]
### Description

Let's rename them `buildTheThing` rather than `getTheThing`. See discussion https://github.com/cagov/ui-claim-tracker/pull/307#discussion_r669850557

### Acceptance Criteria

- [ ] Use `getTheThing` for calling someone and `buildTheThing` when constructing something ourselves

**Comment by lomky** [comment]
I think we've moved past this - closing as wontfix
