### ISSUE TITLE
Track analytics for individual scenarios

### ISSUE THREAD

**Issue by nicoleslaw** [cagov/ui-claim-tracker#327]
### Description

Diana and I would like to be able to see Google analytics (GA) for individual scenarios. I could see us doing this with a tag by scenario or an invisible label, or by using the status label (first h3) itself to differentiate what we're showing to the claimant. While our app is 1 page with 6 scenarios of conditional content, we could treat it as 6 pages at the tracking level.

### Goal

- Be able to track how many claimants see individual scenario content
- Measure time on page for individual scenarios (e.g., interview scheduled, generic pending state)

### Acceptance Criteria

- [x] Review GA documentation
- [x] Update the team with findings and a recommendation if it's feasible
- [x] Implement the GA code

**Comment by rocketnova** [comment]
This ticket should include updating the scenario descriptions in `getScenarioContent.ts` to the following:

- Pending Eligibility: Phone Interview Will Be Scheduled
- Pending Eligibility: Phone Interview Scheduled
- Pending Eligibility: Under Review
- Review Required
- No Weeks Available to Certify
- Weeks Available to Certify

And after R2:

- Benefit Year Has Ended
- Pandemic Unemployment Assistance Has Ended
- Disaster Unemployment Assistance Has Ended
- Federal Unemployment Benefits Have Ended
- Pandemic Emergency Unemployment Compensation Has Ended
- Federal-State Extended Duration Benefits Have Ended

CC @dianagriffin
