### ISSUE TITLE
Enable placeholder page on staging

### ISSUE THREAD

**Issue by kalvinwang** [cagov/ui-claim-tracker#328]
### Description

Goal #1: to continue to allow EDD, CDT, Nava internal folks to be able to view the Claim Tracker (as real as possible, with placeholder content), by simply visiting the staging URL. This makes it much easier to share the link for debugging etc., vs requiring a special setup or instructions.

Goal #2: to prevent anyone outside of EDD, CDT, and Nava from viewing the Claim Tracker w/placeholder content, primarily so they don’t mistake it for real content.

Use the Placeholder Page proposal doc to implement

### Acceptance Criteria

- [ ] Placeholder page working on staging

**Comment by JessiBull** [comment]
@kalvinwang can you add the milestone that this maps to? this ticket wasn't in our sprint discussion today

**Comment by kalvinwang** [comment]
@JessiBull added!
