### ISSUE TITLE
Add final missing translation strings

### ISSUE THREAD

**Issue by rocketnova** [cagov/ui-claim-tracker#346]
### Description

While working on #329, I identified that we're missing a handful of Spanish translation strings. I've notified @nicoleslaw about it and I'm opening this ticket to capture the work.

### Acceptance Criteria

- [x] All remaining Spanish translation strings have been added:
  - [x] "Your Next Steps" — `Sus próximos pasos`
  - [x] "EDD Next Steps" — `Próximos pasos de EDD`
  - [x] Confirm all "EU#" extension types — see [doc](https://docs.google.com/document/d/18ZIc1y8kq9AGxdNCVIyGKWMk5aanBz0p5SaPj2prGPc/edit#)
  - [x] "California Extended Duration (CAL-ED)" — `Duración de la Extensión de California (CAL-ED)`
  - [x] "Interstate Unemployment Insurance" — `Interestatal del Seguro de Desempleo`
  - [x] "NAFTA Transitional Assistance" —`Asistencia de transición del TLCAN`

**Comment by nicoleslaw** [comment]
Hi Rocket, I've updated this doc to match your questions based on EDD's existing content. I will also confirm with their translation team: https://docs.google.com/document/d/18ZIc1y8kq9AGxdNCVIyGKWMk5aanBz0p5SaPj2prGPc/edit#

**Comment by rocketnova** [comment]
> Hi Rocket, I've updated this doc to match your questions based on EDD's existing content. I will also confirm with their translation team: https://docs.google.com/document/d/18ZIc1y8kq9AGxdNCVIyGKWMk5aanBz0p5SaPj2prGPc/edit#

@nicoleslaw You are fantastic. ❤️ Thank you!
