### ISSUE TITLE
Add environment variables to prod 

### ISSUE THREAD

**Issue by kalvinwang** [cagov/ui-claim-tracker#354]
### Description

Add our custom environment variables to prod, and then test them. Currently, they don't exist.

### Acceptance Criteria

- [x] Test that environment variables are working on prod.

**Comment by rocketnova** [comment]
Closing this ticket. 

I did the following:
- Researched all Azure env vars and documented them in the Foundations doc
- Created and updated the environment variables on prod
- Made all env vars consistent for all Azure environments
- Deployed the latest commit on `main` to all Azure environments
- Tested with 1+ unique numbers against all Azure environments 
- Verified that logs were working correctly for all Azure environments for both App Service and App Insights
  - Prod logs were a little wonky so I made a config change yesterday and verified the logs are working for prod correctly today
  - Only remaining outstanding issue are the Internal App Service logs. I've emailed CDT about this

Some new tickets were created out of this work:
- #385 
- #386 
- #387 
- #388

**Comment by rocketnova** [comment]
Marking this ticket as ready for review.

**Comment by rocketnova** [comment]
Closing this ticket. @lomky let me know they reviewed this work and it looks good.
