### ISSUE TITLE
Lighthouse is currently failing

### ISSUE THREAD

**Issue by rocketnova** [cagov/ui-claim-tracker#361]
### Description

During the release process, the Lighthouse runs have been failing starting with [release-101](https://calenterprise.visualstudio.com/UI-Claim-Tracker/_releaseProgress?_a=release-pipeline-progress&releaseId=145) on July 20. I believe this is a firewall issue related to the recent changes to the firewall

### Acceptance Criteria

- [x] Lighthouse succeeds during release

**EDIT:** This ticket is being re-purposed towards removing Lighthouse from the build process.

**Comment by kalvinwang** [comment]
Fixed and documented in Technical Foundations under Accessibility Scan

**Comment by rocketnova** [comment]
Lighthouse has been failing again. The fix is no longer working. We've discussed this and decided that it would be better to remove Lighthouse from the build process.

**Comment by rocketnova** [comment]
CDT will disable Lighthouse from the automated build. We will check in again in a couple weeks to see if we can remove it from the automated build process altogether.
