### ISSUE TITLE
What database should we use?

### ISSUE THREAD

**Issue by kalvinwang** [cagov/ui-claim-tracker#37]
### Description

Research and decide what database we should use

### Acceptance Criteria

  - [x]   Update Claim Tracker Technical Planning doc with research, decision, and justification. Include the database we'd like to use in our request to CDT when setting up the new environment

**Comment by kalvinwang** [comment]
We’re going with CosmosDB again, since we don’t actually know what we’ll be storing yet, beyond likely the BPO ID and a session ID; we’ll probably be storing some kind of status fields, but we don’t know what status fields. And, we aren’t likely to need to do any complex queries since we explicitly want to rely on UIMOD as the source of truth. For details, see the Claim Tracker Technical Planning doc.

**Comment by rocketnova** [comment]
@kalvinwang Can this issue be closed?
