### ISSUE TITLE
Create maintenance page

### ISSUE THREAD

**Issue by kalvinwang** [cagov/ui-claim-tracker#376]
### Description

Be able to enable a maintenance page by setting an environment variable

We’ll only manually enable the maintenance page / it will only be shown when a) something is seriously wrong, and b) EDD has not yet flipped their switch to hide the links to the claim tracker (edit: or claimants visit their bookmark of the claim tracker directly). So this page should be seen rarely, much less often than, say the custom 500 error page.

### Acceptance Criteria

- [ ] Test maintenance page on staging

**Comment by nicoleslaw** [comment]
Here is a quick suggestion based on some UI Online content but I can follow up with UIB soon for any updates. cc @dianagriffin for input

—

## We’ll be back soon

This page is currently unavailable during scheduled system maintenance. Thank you for your patience as we continue to improve our services.
