### ISSUE TITLE
Create proposal for security/maintenance release process post-launch

### ISSUE THREAD

**Issue by kalvinwang** [cagov/ui-claim-tracker#378]
### Description

Create proposal for Azure release process with EDD as the audience (e.g. what sorts of testing we think it makes sense to have for what types of changes)

### Acceptance Criteria

- [x] Get signoff on process from EDD

**Comment by lomky** [comment]
Reference [Eng Notes from 08-16](https://docs.google.com/document/d/1kCPSRS2ld1FirhGvpYTAU9TUM90wbsCvgqt18Z9EIMM/edit#heading=h.vm0rqnkigo9i)

**Comment by dianagriffin** [comment]
Proposal approved 10/28/21: https://docs.google.com/document/d/12q3e-DB8GRIsB1FVO1Xe9_rtsQvty2IzP7-BR4XJn6U/edit#heading=h.eufjse41iwvi
