### ISSUE TITLE
Set up Health Check in App Service

### ISSUE THREAD

**Issue by kalvinwang** [cagov/ui-claim-tracker#396]
### Description

Set up Health Check in App Service on test and production. Instructions here: https://docs.microsoft.com/en-us/azure/app-service/monitor-instances-health-check

"Health check increases your application's availability by re-routing requests away from unhealthy instances, and replacing instances if they remain unhealthy."

Use the /claimstatus/api/health endpoint.

### Acceptance Criteria

- [ ] Verify health check is active on test and prod

**Comment by rocketnova** [comment]
@kalvinwang The documentation you linked says: 
> Health check increases your application's availability by re-routing requests away from unhealthy instances, and replacing instances if they remain unhealthy. Your App Service plan should be scaled to two or more instances to fully utilize Health check. 
> ...
> When given a path on your app, Health check pings this path on all instances of your App Service app at 1-minute intervals.
If an instance doesn't respond with a status code between 200-299 (inclusive) after two or more requests, or fails to respond to the ping, the system determines it's unhealthy and removes it.

What benefits does Health check provide in the case where we are only using one instance? What is the impact of App Service automatically removing an instance if it deems the instance to be unhealthy?

**Comment by rocketnova** [comment]
Closing. This feature does not seem to provide any benefits for our application.
