### ISSUE TITLE
Identify and review existing status content / identify gaps

### ISSUE THREAD

**Issue by AngelQuicksey** [cagov/ui-claim-tracker#4]
### Details / Context

- Review status work from past task orders
- Identify questions for the team and gaps in current information

### Acceptance Criteria
- [x] Team understands existing content artifacts
- [x] Questions are documented for collaborative session with CA EDD stakeholder

**Comment by nicoleslaw** [comment]
I added some more questions to our claim status database and design questions docs, and Angel is planning to reach out to WCUG to schedule our initial call next week.
