### ISSUE TITLE
Display "None" if lastPaymentIssued or lastPaymentAmount returns null

### ISSUE THREAD

**Issue by dianagriffin** [cagov/ui-claim-tracker#419]
### Description

This ticket updates behavior that was implemented in #365 related to the Last Payment Issued field. We have since learned that in UIO, this field displays "None" when null, and the requirement is to match that functionality in the Claim Tracker.

In the Claim Details display, "Last Payment Issued" combines data from `lastPaymentIssued` and `lastPaymentAmount`. If either field returns null, we should display the field value as "None" for "Last Payment Issued". 

Currently, we hide the display field when either API field returns null, so this ticket is to update the behavior to display "None" under these conditions instead of hiding the field. 

### Acceptance Criteria

- [ ] When either lastPaymentIssued of lastPaymentAmount returns null, the field value for Last Payment Issue under Claim Details displays as "None"

**Comment by nicoleslaw** [comment]
For Spanish, let's do: `Ninguno`
