### ISSUE TITLE
Choose and integrate an accessibility scanner for development

### ISSUE THREAD

**Issue by lomky** [cagov/ui-claim-tracker#43]
### Description

Integrate a accessibility scan harness into the UI Claim Tracker application. By default we are leaning towards [eslint-plugin-jsx-a11y](https://www.npmjs.com/package/eslint-plugin-jsx-a11y) like our [previous project](https://github.com/cagov/unemployment), but we should do a bit of research if there is some NextJS bonus or other best practice that has emerged.

### Acceptance Criteria

  - [x] Confirmed eslint-plugin-jsx-a11y is a reasonable choice for our project
  - [ ] Integrated eslint-plugin-jsx-a11y into the project base
  - [ ] Document choices in our [Technical Foundations doc](https://docs.google.com/document/d/1i2pj7_3n0VjqqztOepkd2VcG7JA8N9Tg5P76GSI8tzw/edit#)

**Comment by kalvinwang** [comment]
Going to timebox this to a couple hours, if it takes longer we can rely on Lighthouse till post-MVP or when we have more capacity
