### ISSUE TITLE
Strip trailing slashes from environment variable URLs

### ISSUE THREAD

**Issue by kalvinwang** [cagov/ui-claim-tracker#438]
### Description

The presence or absence of a trailing slash on an environment variable that contains a URL shouldn't affect anything, but it does, at least for API_URL. (The endpoint needs to be `path?x=y` not `path/?x=y`). We can update our code to strip trailing slashes in case one is accidentally added in App Service App Settings again. 

Edit: moved the task for removing trailing slashes from other env vars to #424, to reduce the risk of this change

### Acceptance Criteria

- [ ] Remove trailing slashes that might appear in environment variables

**Comment by rocketnova** [comment]
A trailing slash in the `API_URL` env var will cause the standard availability tests failures (status code return 404). The standard availability tests on Prod were universally failing up until 8/30/21 @ 11:22am PT when we stripped the trailing slash.
