### ISSUE TITLE
Missing Application Insights env var results in unexpected page render

### ISSUE THREAD

**Issue by rocketnova** [cagov/ui-claim-tracker#468]
### Description

While working on #432, I discovered that when the App Insights environment variable is missing, CST displays the following:

![Screen Shot 2021-09-08 at 4 19 02 PM](https://user-images.githubusercontent.com/67701/132598040-4e76bcb4-1c82-4270-a184-5161b7670192.png)

This is unexpected.

### Acceptance Criteria

- [x] Identify what's going on
- [x] Make any necessary fix so that a missing App Insights env var renders nicely

**Comment by rocketnova** [comment]
@lomky (CC @nicoleslaw @dianagriffin). It turns out that when an error is thrown and we do not catch it, this is what is displayed (see ticket description). Is this an issue we want to fix? I think it's pretty rare, but still possible that we may have uncaught errors and we probably want to display something nicer. If so, can you open a new ticket for it?

Details: It turns out that this `throw new Error` wasn't getting caught and was resulting in this render. https://github.com/cagov/ui-claim-tracker/blob/72d5437615433f590f792d12461ad9c9290355ab/utils/logger.ts#L81-L84

**Comment by nicoleslaw** [comment]
I can open a ticket on this one. @dianagriffin do you think it makes sense to display the 500 message here even though it's not a 500 error?

<img src="https://user-images.githubusercontent.com/94900/132554947-8cdb9167-1dd2-4307-baab-07f8eae68294.png" width="600" />

Relates to #467

**Comment by dianagriffin** [comment]
@nicoleslaw I agree that the 500 message is generic enough to make sense/be generally accurate from the user perspective.
