### ISSUE TITLE
Have UIO stop intercepting errors with the BPO error page

### ISSUE THREAD

**Issue by kalvinwang** [cagov/ui-claim-tracker#474]
### Description

Claim Tracker 500 "Internal server error" pages will never display, since IDM redirects to the BPO error page, when IDM intercepts a 500 from Claim Tracker. However, Claim Tracker does log the 500 error as intended, so the only difference is that the user sees a BPO error page instead of the Claim Tracker error page.

We want to do this so that it's easier to attribute Claim Tracker errors when a Claim Tracker-specific error page is displayed, instead of the generic BPO error page.

See email thread "Claim Status Tracker - potential issue"

### Acceptance Criteria

- [ ] Work with IDM team to have IDM stop intercepting errors (preferred), OR return 500s instead of 503s (not preferred)

**Comment by rocketnova** [comment]
Closing. Won't fix.
