### ISSUE TITLE
Eliminate SNAT port exhaustion under load

### ISSUE THREAD

**Issue by kalvinwang** [cagov/ui-claim-tracker#478]
### Description

We’ve addressed SNAT port exhaustion in multiple ways (implementing keep-alive on API gateway and App Insights calls; disabling Live Monitor in all envs other than prod) and CDT addressed it by putting the Claim Tracker app on its own App Service plan away from BNSCN / last year’s app. We could fine-tune some of this, but I think the low-hanging fruit is gone. And under high loads, the number of SNAT ports needed is still far higher than what’s available, which results in pending and failed SNAT connections.

This [Virtual Network NAT solution](https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-outbound-connections#associating-a-nat-gateway-to-the-subnet) is the "Best" Microsoft recommended solution, and CDT offered to look into implementing it, so we should take them up on it. (I'm not certain that link is the right one because I don't know if an Azure public load balancer is what Azure Front Door uses for load balancing, but it should be something similar).

> Virtual Network NAT simplifies outbound-only Internet connectivity for virtual networks. When configured on a subnet, all outbound connectivity uses your specified static public IP addresses. Outbound connectivity is possible without load balancer or public IP addresses directly attached to virtual machines. NAT is fully managed and highly resilient.
> 
> Using a NAT gateway is the best method for outbound connectivity. A NAT gateway is highly extensible, reliable, and doesn't have the same concerns of SNAT port exhaustion.

### Acceptance Criteria

- [ ] Confirm SNAT port exhaustion is eliminated under load

**Comment by lomky** [comment]
CDT recommend looking into Application Pooling - it'd be best to avoid VN NATs as it would be overkill for us

[Improper Instantiation antipattern (Code sample included)](https://appserviceblog.com/en/snat-app-services-2/)
[Troubleshooting intermittent outbound connection errors in Azure App Service](https://4lowtherabbit.github.io/blogs/2019/10/SNAT/)
[Understanding SNAT with App Service](https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-intermittent-outbound-connection-errors#avoiding-the-problem)
[SNAT App Services – App Service Blog](https://docs.microsoft.com/en-us/azure/architecture/antipatterns/improper-instantiation/#how-to-fix-the-problem)

**Comment by lomky** [comment]
We have an existing example of singleton/static with our [pino logger setup](https://github.com/cagov/ui-claim-tracker/blob/d30ff5e8a5417eb273a7bb0b4c14b430a8dcdcb7/utils/logger.ts#L35-L43) - I'll confirm that behavior persists across requests and investigate implementing the same for our [HTTP agent instantiation](https://github.com/cagov/ui-claim-tracker/blob/d30ff5e8a5417eb273a7bb0b4c14b430a8dcdcb7/utils/queryApiGateway.ts#L149)

**Comment by lomky** [comment]
We are no longer seeing SNAT Port exhaustion in production:
![SNAT Port Exhaustion report in Production showing no issues](https://user-images.githubusercontent.com/6129479/139867924-5a292dd1-efe4-49a9-b800-97c8466e6eb5.png)
