### ISSUE TITLE
Prep for huddle presentation

### ISSUE THREAD

**Issue by nicoleslaw** [cagov/ui-claim-tracker#489]
### Description

We are presenting the Claim Tracker project to Navanauts on October 1 in our company-wide huddle. We have 30min to talk and 10min for Q&A with the audience.

### Acceptance Criteria

- [x] Set up call to plan and discuss
- [x] Finalize [agenda](https://docs.google.com/document/d/152OHdzCMCx4J6y6Z5cok5rpWVHnxGaqoM69HQ6Dpu1M/edit#) with the team
- [x] Pair with Diana when she is back from PTO
- [x] Prep any slides or data we need

**Comment by nicoleslaw** [comment]
@nikkibrand I found this [huddle agenda](https://docs.google.com/document/d/1tmSMYIZYUike8vBVJTfRG3iGHkwE0LIz_y86ukSKAKM/edit) from PFML—sharing in case it's a useful reference!

**Comment by nikkibrand** [comment]
@nicoleslaw I made a few changes to the panel questions and divided them up into questions we definitely want to cover, and additional questions if audience Q&A is limited. Also blocked out some space for the team to put in more details for each section.

**Comment by nikkibrand** [comment]
Tuesday works! I'll set it up.
