### ISSUE TITLE
Implement the UIO global header in CST

### ISSUE THREAD

**Issue by nicoleslaw** [cagov/ui-claim-tracker#491]
### Description

Implement the UIO header in the CST. Relates to #490. The icon is `ca-gov-icon-file-medical-alt` via [CA's font library](https://www.cdfa.ca.gov/v6.5/sample/icon-fonts.html).

Based on the threads with EDD and WCUG, the new label is `Status` and `Estatus de solicitud` for Spanish.

![image](https://user-images.githubusercontent.com/94900/133822531-bacd09e1-f92e-4f81-a4b7-cd0a67297731.png)

### Acceptance Criteria

- [ ] Build the header (behind a feature flag?)
- [ ] Implement the UIO links after UIO updates
- [ ] Test and tag design for testing

### Icons in header order

- ca-gov-icon-home
- ca-gov-icon-file-check
- ca-gov-icon-currency
- ca-gov-icon-clock
- ca-gov-icon-file-medical-alt
- ca-gov-icon-person
- ca-gov-icon-email
- ca-gov-icon-users-dialog

### Spanish labels in order
- UI Inicio
- Certificar
- Pagos
- Historial
- Estatus de solicitud
- Perfil
- Buzón
- Contáctenos

**Comment by nikkibrand** [comment]
Mobile View:
![image](https://user-images.githubusercontent.com/89538179/134418304-1ab93f04-30be-415c-a7df-91f1afb16372.png)

![image](https://user-images.githubusercontent.com/89538179/134418566-01d75627-7603-4bc4-8554-4b412aa34b36.png)

**Comment by nikkibrand** [comment]
Mobile Version:

<img src="https://user-images.githubusercontent.com/89538179/134419270-486c7d63-914c-4046-a1ef-7a288f449381.png" width="200" height="450"> <img src="https://user-images.githubusercontent.com/89538179/134418992-51e96d58-e619-4239-882c-e2d766e599f1.png" width="200" height="450">
