### ISSUE TITLE
Update error pages with revised designs

### ISSUE THREAD

**Issue by nicoleslaw** [cagov/ui-claim-tracker#509]
### Description

Relates to #467

### Acceptance Criteria

- [ ] Implement updated error page designs
- [ ] Pair with @nikkibrand on visual QA
- [ ] Confirm with @dianagriffin and UIB we're ready to ship

**Comment by nikkibrand** [comment]
**404 Error**

<img src="https://user-images.githubusercontent.com/89538179/136083923-a2187426-f543-446c-95f1-16701b6f11c6.png" width="300" height="225">  <img src="https://user-images.githubusercontent.com/89538179/136084022-eddbab4b-efd4-4edf-b90d-652ecceaca5f.png" width="90" height="225">

**500 Error**
<img src="https://user-images.githubusercontent.com/89538179/136084223-3eff7c91-1204-4e05-a385-06b2ff50afe6.png" width="300" height="225"> <img src="https://user-images.githubusercontent.com/89538179/136083583-421aa021-5055-4253-ba4d-57d24b708053.png" width="90" height="225">

**Maintenance**
<img src="https://user-images.githubusercontent.com/89538179/136083361-4d8b397d-c95b-4346-ac48-373433ee7019.png" width="300" height="225"> <img src="https://user-images.githubusercontent.com/89538179/136084112-9ad524ec-9a24-4cad-bd28-748ad1870597.png" width="90" height="225">

**Comment by rocketnova** [comment]
Closing :(
