### ISSUE TITLE
Figure out how we want to use browser analytics

### ISSUE THREAD

**Issue by lomky** [cagov/ui-claim-tracker#51]
### Description

- Ideally we'd get a baseline for whatever we want to measure changes in
Setup Google Analytics. See implementation details from the unemployment repo, and coordinate with EDD/CDT to confirm configuration details.

### Acceptance Criteria

  - [ ] Document where we want Google Analytics events set up on both UIO and Claim Tracker (work with product/design)
  - [ ] Results are sent to CA partners as directed
  - [ ] Document setup in our [Technical Foundations doc](https://docs.google.com/document/d/1i2pj7_3n0VjqqztOepkd2VcG7JA8N9Tg5P76GSI8tzw/edit#)

**Comment by dianagriffin** [comment]
Once our team gets GA access, we'll walk through what they're already tracking and figure out what else we want to track as a baseline

**Comment by dianagriffin** [comment]
Default GA tracking will be adequate for MVP release. Ticket to add GA here: https://github.com/cagov/ui-claim-tracker/projects/1#card-65004867
