### ISSUE TITLE
Add final Content for BYE Scenarios

### ISSUE THREAD

**Issue by lomky** [cagov/ui-claim-tracker#519]
### Description

Add final content provided by EDD for the BYE Scenarios, (Scenarios 7-10).

Draft content was added in #516 

### Acceptance Criteria

- [x] Final English content added
- [x] Final Spanish content added
- [x] PR is based on the `future` branch

**Comment by dianagriffin** [comment]
Final English content: https://docs.google.com/document/d/1sKk3_k4_uwtIBVvosaKybs05nzvFdtTR/edit#heading=h.un4vy1cwkfcz

Final Spanish content: https://docs.google.com/document/d/1vzc7-yXVj5AGqJb8C7vYXMpqK36r0UUe/edit#heading=h.gjdgxs

**Comment by rocketnova** [comment]
Merged #543
