### ISSUE TITLE
Setup securely shared .env file

### ISSUE THREAD

**Issue by lomky** [cagov/ui-claim-tracker#52]
### Description

Setup a `.env` file with needed secrets for development and share via the "CA UI Eng sensitive" vault

Known envs:
  - cosmo connection details

### Acceptance Criteria

  - [ ] development secrets shared securely
  - [ ] Document setup in our [Technical Foundations doc](https://docs.google.com/document/d/1i2pj7_3n0VjqqztOepkd2VcG7JA8N9Tg5P76GSI8tzw/edit#)

**Comment by kalvinwang** [comment]
Merged into #54
