### ISSUE TITLE
Simplify business logic flow if isBye is always returned by the API

### ISSUE THREAD

**Issue by lomky** [cagov/ui-claim-tracker#524]
### Description

If it turns out that `isBye` is a garunteed field in the API response, we can simplify several pieces of logic, as noted by @rocketnova in #516. We will also need to update our 'null' error reponse catches to expect it.

This work is blocked until we see how the API handles the new field.

### Acceptance Criteria

- [ ] Simplify business logic if BYE is garunteed
- [ ] Update base API response expectations

**Comment by rocketnova** [comment]
Moving out of R2 feature release per conversation on 11/10 with @lomky
