### ISSUE TITLE
Document updating an existing scenario

### ISSUE THREAD

**Issue by lomky** [cagov/ui-claim-tracker#550]
### Description

Create a Technical Runbook for how to update the language, links, or logic for a generic already existing scenario

### Acceptance Criteria

- Another engineer could
  - [x] update the language for an existing scenario
  - [x] could update the links for an existing scenario
  - [x] know where to go to update logic for an existing scenario

**Comment by lomky** [comment]
First pass finished - leaving this open for a second pass after we write the URL Tech Spec (or this work is migrated to another list!)

**Comment by rocketnova** [comment]
Closing this in favor of https://github.com/cagov/ui-claim-tracker-technical-documentation/issues/1
