### ISSUE TITLE
Document creating a new scenario

### ISSUE THREAD

**Issue by lomky** [cagov/ui-claim-tracker#551]
### Description
Create a Technical Runbook for how to create a new scenario, generally.

### Acceptance Criteria

- Another engineer could:
  - [ ] add content for a new scenario
  - [ ] add links that follow existing patterns, for a new scenario
  - [ ] be able to recognize links that require new logic
  - [ ] know where to go to add logic for a new scenario

**Comment by rocketnova** [comment]
Closing this in favor of https://github.com/cagov/ui-claim-tracker-technical-documentation/issues/1
