### ISSUE TITLE
Logout bug: returning to CST url immediately after logging out still loads the page

### ISSUE THREAD

**Issue by dianagriffin** [cagov/ui-claim-tracker#577]
### Description
EDD emailed about this issues reported by an internal EDD tester.

> Here are the steps to recreate the issue:
>  
> 1. Log into UIO
> 2. Click on the Status link to navigate to CST
> 3. Click Log Out on the CST page
> 4. In the browsers address bar, enter the URL for the CST.
> 5. If done quick enough, the CST page will load with the signed out users information.
>  
> To me it seems like an issue where the user isn’t fully logged out so Idm is still sending the unique number.
> 
> Would someone be able to look into this and see if there is anything we can do to address the issue?

### Acceptance Criteria

- [ ] Investigate issue and recommend resolution (or implement fix if LOE allows)

**Comment by rocketnova** [comment]
Can't fix. This is an upstream issue based on what IDM sends to the CST. We have responded to EDD.
