### ISSUE TITLE
Implement language-based urls for Help link in top navbar

### ISSUE THREAD

**Issue by dianagriffin** [cagov/ui-claim-tracker#579]
### Description

Update the "Help" link to use the `edd-help-new-claim` url for English and the `edd-help-new-claim-spanish` url for Spanish - see [this spreadsheet](https://docs.google.com/spreadsheets/d/1I7Jq2EaHuhlSCfuOI3uRKjNvBDdF1EN04E7XeaLqkCQ/edit#gid=0h) for the list of these urls by environment. 

### Acceptance Criteria

- [ ] "Help" links to the appropriate urls for English and Spanish as documented in [this spreadsheet](https://docs.google.com/spreadsheets/d/1I7Jq2EaHuhlSCfuOI3uRKjNvBDdF1EN04E7XeaLqkCQ/edit#gid=0)

**Comment by kalvinwang** [comment]
This was resolved by #582 which was merged into main last week
