### ISSUE TITLE
Implement modal for external links to be consistent with UIO behavior

### ISSUE THREAD

**Issue by dianagriffin** [cagov/ui-claim-tracker#580]
### User Story
As a claimant, I want to be aware when a link I've clicked a link that will take me out of UIO, so that I can choose to proceed or stay focused on what I'm doing in UIO.

### Details / Context
Within UIO, links to external sites e.g. the EDD website prompt the user with a modal before opening the external site in a new tab. The CST page needs to have the same functionality implemented for consistency with UIO.

### Acceptance Criteria

  - [ ] When a user clicks any link to an external site (ie. any link that does not link to a UIO page), a modal pops up.
  - [ ] The modal has the same content, look & feel as the modal that exists for this purpose in UIO.

**Comment by lomky** [comment]
Example of the modal:
![External Link modal](https://user-images.githubusercontent.com/6129479/146803881-7aa42b9e-9634-46d7-a37f-f43d961249a9.png)

**Comment by lomky** [comment]
@dtodd-edd @AmarjeetLitt 
[Here is the branch with the work we did in the pairing session!](https://github.com/cagov/ui-claim-tracker/tree/580_external_link_modal)

And the referenced links:
  - [Component Driven Design](https://www.componentdriven.org/)
  - [the Bootstrap modal object](https://getbootstrap.com/docs/5.1/components/modal/) - also shows the onClick behavior

**Comment by kalvinwang** [comment]
@dtodd-edd took on this task last week, so I'm moving it to in-progress!
