### ISSUE TITLE
Gather claim status system data

### ISSUE THREAD

**Issue by AngelQuicksey** [cagov/ui-claim-tracker#7]
### Task
Request claim data from CA EDD

### Details / Context
_This might include:_ 
- Customer satisfaction 
- Measures of customer sentiment
- Visits to the claim status page vs other pages
- Drop off points / bounce rate

### Acceptance Criteria
- Data has been requested and received (if it exists)

**Comment by dianagriffin** [comment]
We have made a broad request for data and will continue to pursue this request in other channels.
