### ISSUE TITLE
Figure out subdomain name

### ISSUE THREAD

**Issue by kalvinwang** [cagov/ui-claim-tracker#71]
### Description
We should figure out the desired subdomain name for the Claim Tracker app, and work with EDD and CDT to implement it

It can be a subdomain of *.edd.ca.gov (like unemployment.edd.ca.gov last year); it may be possible to be under *.uio.ca.gov; it's unlikely we can get anything under *.ca.gov though I'm not sure why we'd want to, since we want to match UIO.

### Acceptance Criteria

- [ ] Figure out desired subdomain
- [ ] Work with EDD to set up DNS
- [ ] Work with CDT to add to Azure production app

**Comment by dianagriffin** [comment]
We should propose a 1-2 character option that would be unobtrusive to claimants. If EDD doesn't go for that, we'll also have 1-2 options with a generically descriptive word

**Comment by rocketnova** [comment]
@dianagriffin Can this issue be closed?
