### ISSUE TITLE
Build header and footer to match EDD/UIO

### ISSUE THREAD

**Issue by kalvinwang** [cagov/ui-claim-tracker#74]
### Description
Design team is figuring out what EDD wants in terms of the header and footer (should it match EDD's header and footer, v5.5, or UIO's header and footer, etc). See [Slack thread for context](https://nava.slack.com/archives/C01Q5640YFR/p1616518282031100)

If it should match EDD, we can build on our header and footer from last year, which was a partial, simplified reconstruction of the EDD header.

### Acceptance Criteria

  - [ ]  Header and footer matching desired template, fully functional and deployed to staging

**Comment by nguyen-tina** [comment]
Please see ticket #59 for decision! (Match EDD's header + footer)

**Comment by nguyen-tina** [comment]
Question-- does the header change behavior when you view the bottom half of page, vs. when you land the page and see the header immediately? There's slight interaction design there (of transitioning to the "compressed" header) and wanted to get on the same page of which one you've deveveloping.

**Comment by nguyen-tina** [comment]
that's fine! Let's stick with this more simple, non-interactive header and avoid adding icons yet.
