### ISSUE TITLE
With UIB input, identify and prioritize scenarios (ie. claim issues) that would set more than one week to "pending" 

### ISSUE THREAD

**Issue by dianagriffin** [cagov/ui-claim-tracker#75]
### Description
Identify and prioritize the scenarios (ie. claim issues) that would set more than one week to "pending" so that our MVP scope is clearly defined.

Tactics for achieving this: 
- requested list from UIB 
- working sessions with UIB
- exploring CUBS in the test environment to surface hypotheses for UIB to confirm

### Acceptance Criteria
- We have a confirmed list of scenarios that set more than one week to "pending" (ie. they have claim-level issues that will prevent any upcoming payments until they are resolved).
- We have categorized the list into scenarios the Claim Tracker will address individually or scenarios that can be bucketed together to address in the Claim Tracker.

**Comment by AngelQuicksey** [comment]
Vicki just gave us names for working sessions! cc @nicoleslaw

**Comment by AngelQuicksey** [comment]
I just requested available time slots for Mon, Tue, or Wed with the names from Vicky

**Comment by AngelQuicksey** [comment]
Next meeting is scheduled for today (Apr 6). @dianagriffin will take point on coordinating future sessions. See notes from design braintime ([notes](https://docs.google.com/document/d/1Zfe9ayAUj2EkyOHsxGJWPYc1FCB2e-b8QqUuHRD5-Io/edit#bookmark=id.eqj4r4z8l6f3))

> Owning business logic working sessions – who schedules, plans, follows up, etc. 
> – Diana wants to make the UIB + Nava working session recurring. This is a target outcome for today's session.
> – Diana to manage the high-level coordination though each session will have an owner depending on the topic. _Diana will choose the owner, inform them and update delivery as needed._

**Comment by dianagriffin** [comment]
See spreadsheet: https://docs.google.com/spreadsheets/d/14Ty0TVFJEyXYUGRUbumS-sofSOf9sMhn/edit#gid=750380537
