### ISSUE TITLE
Define implementation steps for SAML in detail

### ISSUE THREAD

**Issue by kalvinwang** [cagov/ui-claim-tracker#76]
### Description
@dgoeke created an initial task breakdown in the IDM integration doc. Now we need to flesh it out and figure out which pieces will be done for us by the authentication library we select (likely Passport) and ticket the other pieces.

### Acceptance Criteria

  - [x] Create tickets for tasks associated with the Nava SAML implementation portion of IDM integration

**Comment by kevmo** [comment]
# Issues (editing this comment as I add them):

* https://github.com/cagov/ui-claim-tracker/issues/80
*

**Comment by rocketnova** [comment]
@kalvinwang Can this ticket be closed?
