### ISSUE TITLE
Gather claim status query data (call centers)

### ISSUE THREAD

**Issue by AngelQuicksey** [cagov/ui-claim-tracker#8]
### Task
Request data from CA EDD: requests or questions from claimants related to claim status

### Details / Context
_This might include:_ 
- No. of calls to CA EDD call centers related to claim status
- Time spent on CA EDD call center calls related to claim status
- Relative to # of open claims
- Relative to all calls (as a percentage of calls)

### Acceptance Criteria

- Data has been requested and received (if it exists)

**Comment by dianagriffin** [comment]
On 3/5 I sent Supreet and Jeet a broad request for data and metrics related to claims, claim processing, and claim-related support channels (especially the call center). I followed up today to confirm Lynn Grogan is the person to contact about call center reporting, and once confirmed, I will reach out to Lynn with this request.

**Comment by dianagriffin** [comment]
Closing this ticket although we have not yet received a response to the request. We're continuing to surface it as an ask in our weekly status report and will reiterate the request through other channels.
