### ISSUE TITLE
Select an authentication library for supporting SAML 2.0 & incorporate it into codebase. 

### ISSUE THREAD

**Issue by kevmo** [cagov/ui-claim-tracker#80]
### Description
SAML 2.0 is an old standard & there are various node libraries for supporting it:
- [Passport](http://www.passportjs.org/) is the most popular library and package of choice for many. [Passport-saml](http://www.passportjs.org/packages/passport-saml/) is a well-maintained package. 
- [NextAuth.js](https://next-auth.js.org/) is made specifically for Nextjs, but it appears to require more 3rd-party software to use SAML. 

Pick one.  Incorporate it into the codebase.

### Acceptance Criteria

  - [ ] package.json updated
  - [ ] package is configured to be used as middleware.

**Comment by kalvinwang** [comment]
Closing #80, #81, #82, #83 since we're switching to the IDM team's proxy authentication approach. Can re-open if ever needed.
