### ISSUE TITLE
Add identity service provider mock for testing Single Sign-On workflow. 

### ISSUE THREAD

**Issue by kevmo** [cagov/ui-claim-tracker#81]
### Description
 
Single-sign on is an important aspect of this application -- the entire app will not work if it does not. 

### Acceptance Criteria

  - Create tests that allow a moderate level of confidence that our service provider SAML flows works as long as the Identity Provider is worker.
  - Potentially use this to make code more robust in the event of IdP failure (could become it's own issue)

**Comment by kalvinwang** [comment]
Closing #80, #81, #82, #83 since we're switching to the IDM team's proxy authentication approach. Can re-open if ever needed.
