### ISSUE TITLE
Create `/acs` endpoint which authenticates or rejects SAML assertions. 

### ISSUE THREAD

**Issue by kevmo** [cagov/ui-claim-tracker#82]
### Description

This is bulk of SAML work. 

When an identity provider (BPO) sends SAML assertions, they POST them to a specified endpoint of the service provider (ClaimsTracker).

The ClaimsTracker should then use a Certificate(s) to valid signatures on the SAML responses/assertions from BPO. It is also possible messages may be encrypted.

If the signature is authenticated, ClaimsTracker should display logged-in UX. 

If the signature is not authenticated, ClaimsTracker sends a new authentication request to BPO's SSO URL, and then the flow starts fresh.  Note: This functionality should maximize reusability.  It is possible landing page will eventually develop that says "Click here to log into BPO."

### Acceptance Criteria

  - [ ] `/acs` endpoint created 
  - [ ] SAML assertions extracted and inspected for validity
  - [ ] valid identities should be sent to logged-in view (with information regarding Unique Number?)
  - [ ] invalid assertions will send user back to BPO SSO login endpoint.

**Comment by kalvinwang** [comment]
Closing #80, #81, #82, #83 since we're switching to the IDM team's proxy authentication approach. Can re-open if ever needed.
