### ISSUE TITLE
Coordinate with WCUG to understand required pre-launch testing/review processes

### ISSUE THREAD

**Issue by AngelQuicksey** [cagov/ui-claim-tracker#89]
### Description
@AngelQuicksey will take point on learning the requirements/process for accessibility testing and usability review from WCUG
**See also:** https://github.com/cagov/ui-claim-tracker/issues/30

### Acceptance Criteria
- [ ] Requirements and process identified for accessibility testing and usability review from WCUG

**Comment by AngelQuicksey** [comment]
Sent email to WCUG to tee up intro to accessibility / translation teams.

**Comment by AngelQuicksey** [comment]
Got connected to those teams. Need to ask specific questions about timelines.

**Comment by JessiBull** [comment]
merging this into more comprehensive timeline ticket
