### ISSUE TITLE
Add TLS/SSL certificate to Azure App Service

### ISSUE THREAD

**Issue by kalvinwang** [cagov/ui-claim-tracker#93]
### Description

Add the certificates generated in #88 to our environments

[Add a TLS/SSL certificate in Azure App Service](https://docs.microsoft.com/en-us/azure/app-service/configure-ssl-certificate)

Questions:
- Does adding this change the existing inbound IP address? If yes, we'll need to let the API gateway team know
- Can a different certificate be used per environment? If not, we'll need to let the API gateway team know

### Acceptance Criteria

  - [x] Have the certificates added for each environment, verified, and the questions above answered

**Comment by rocketnova** [comment]
@kalvinwang Can this issue be closed?
