### ISSUE TITLE
Plan out Components and their draft iterations

### ISSUE THREAD

**Issue by lomky** [cagov/ui-claim-tracker#96]
### Description

In the spirit of iterative development, we don't want to wait until our components' designs are fully polished to implement them. Eng and Design should collaborate to figure out an iteration process.

Questions to answer:
 - What components do we need?
 - What are the draft stages, and when should engineering start work?
 - Write out tickets for these.

**Comment by nguyen-tina** [comment]
For reference: [Claim Tracker Component Drafting](https://docs.google.com/document/d/13amWdz6EBwFKOBbQDfXROypE8XQEWxLhUXwfA5qeEj8/edit)
